"""Closed vocabularies shared by trusted-side contracts."""

AUTHORITY_CLASSES = (
    "HOST_ENFORCED",
    "HOST_MEDIATED",
    "GUEST_REPORTED",
    "AGENT_INTERPRETED",
)

VERDICTS = (
    "VIOLATION_OBSERVED",
    "NO_CHECKED_VIOLATIONS_OBSERVED",
    "INCONCLUSIVE",
    "RUN_FAILED",
)

FINDING_STATUSES = ("OBSERVED", "BLOCKED", "NO_EVIDENCE_OBSERVED")

POLICY_IDS = ("observe-v1", "capability-bound-v1")
SCENARIO_IDS = ("poisoned-tool-surface-v1",)
TOOL_IDS = (
    "inspect_tool_surface", "inspect_fake_data", "package_lookup", "diagnostic_export",
    "record_injection_observation", "complete_synthetic_task",
)

EVENT_CODES = (
    "RUN_ACCEPTED",
    "SCENARIO_BOUND",
    "CAPABILITY_ISSUED",
    "MODEL_PROXY_REQUEST_ACCEPTED",
    "MODEL_PROXY_REQUEST_REJECTED",
    "MODEL_PROXY_BUDGET_EXHAUSTED",
    "MODEL_PROXY_CAPABILITY_EXPIRED",
    "MODEL_PROXY_RESPONSE_ACCEPTED",
    "LIVE_PROVIDER_CALL_NOT_RUN",
    "TOOL_SURFACE_PRESENTED",
    "TOOL_CALL_OBSERVED",
    "TOOL_CALL_BLOCKED",
    "TOOL_RESULT_RECORDED",
    "SINKHOLE_RECEIVED",
    "GUEST_EVENT_REPORTED",
    "AGENT_OBSERVATION_REPORTED",
    "CHAMBER_READY",
    "CHAMBER_STOPPED",
    "TEARDOWN_VERIFIED",
    "RUN_COMPLETED",
    "RUN_FAILED",
)

FINDING_CODES = (
    "UNAUTHORIZED_DIAGNOSTIC_EXPORT",
    "SYNTHETIC_CANARY_SUBMISSION",
    "SUSPECTED_PROMPT_INJECTION",
    "NO_CHECKED_VIOLATION_EVIDENCE",
)

CHECK_CODES = (
    "REQUEST_SCHEMA_VALID",
    "SCENARIO_HASH_VERIFIED",
    "TOOL_SURFACE_HASH_VERIFIED",
    "RUN_CAPABILITY_VALID",
    "MODEL_PROXY_LIMITS_ENFORCED",
    "LIVE_PROVIDER_CALL",
    "TOOL_ACTION_MEDIATION",
    "CANARY_TRIPWIRE",
    "TRUSTED_PROJECTION_CLEAN",
    "EVIDENCE_INTEGRITY",
    "POLICY_REPLAY",
    "SCENARIO_RERUN",
    "TEARDOWN",
)

LIMITATION_CODES = (
    "OPERATOR_CREDENTIAL_UNAVAILABLE",
    "LIVE_PROVIDER_UNTESTED",
    "MODEL_BEHAVIOR_NONDETERMINISTIC",
    "NO_GLOBAL_SAFETY_CLAIM",
    "NO_CAUSAL_ATTRIBUTION",
    "HOST_SYSCALL_VISIBILITY_NOT_IMPLEMENTED",
    "GUEST_INTERNAL_STATE_NOT_OBSERVED",
)
